app/__init__.py
# app/__init__.py

from flask import Flask, redirect, url_for
from app.auth.routes import auth_blueprint
from app.mongo import init_mongo
import os

app = Flask(__name__)

# Define the MongoDB URI for local MongoDB instance
mongo_uri = "mongodb+srv://storage:Abhey123@cluster0.i4dedvi.mongodb.net/database"

# Set the MongoDB URI in the Flask app configuration
app.config["MONGO_URI"] = mongo_uri

# secretkey
app.config['SECRET_KEY'] = os.urandom(24)



# Initialize MongoDB connection
init_mongo(app)

# Register the authentication blueprint
app.register_blueprint(auth_blueprint, url_prefix='/auth')

# Define a route for the root URL
@app.route('/')
def index():
    return redirect(url_for('auth.signup'))  # Redirect to signup page when accessing root URL

if __name__ == "__main__":
    app.run(debug=True)

app/upload/__init__.py
from flask import Blueprint

upload_blueprint = Blueprint('upload', __name__)

# Import routes from routes.py
from app.upload import routes

app/upload/routes.py
from flask import request, flash, redirect, url_for, render_template, send_file, make_response, session
from . import upload_blueprint
from azure.storage.blob import BlobServiceClient
import os
import io

# Define your Azure Storage account connection string
connection_string = "DefaultEndpointsProtocol=https;AccountName=storageaccforpythonapp;AccountKey=KjwGJhFFS3eSC/nhS5mAqXqNDYPQwv1E9ElaH9Q2rs1gOsfo6XZgaAwtCjX3uZxZchLuQ8bWVVeA+AStphrmKA==;EndpointSuffix=core.windows.net"
# Define the name of the container in Azure Blob Storage
container_name = "storagecontainer"
# Define the directory for local storage (optional)
local_storage_dir = "local_storage/"

@upload_blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
    if not session.get('logged_in'):
        flash('Please log in to access this page.', 'error')
        return redirect(url_for('auth.login'))

    if request.method == 'POST':
        if 'file' not in request.files:
            flash('No file part', 'error')
            return redirect(request.url)

        file = request.files['file']

        if file.filename == '':
            flash('No selected file', 'error')
            return redirect(request.url)

        try:
            # Save the file to local storage (optional)
            local_file_path = os.path.join(local_storage_dir, file.filename)
            file.save(local_file_path)

            # Upload the file to Azure Blob Storage
            blob_name = file.filename
            blob_service_client = BlobServiceClient.from_connection_string(connection_string)
            container_client = blob_service_client.get_container_client(container_name)
            blob_client = container_client.get_blob_client(blob_name)

            with open(local_file_path, "rb") as data:
                blob_client.upload_blob(data)

            flash('File uploaded successfully!', 'success')

            # Delete the local file after successful upload (optional)
            os.remove(local_file_path)

            return redirect(url_for('upload.upload'))

        except Exception as e:
            flash(f'An error occurred: {e}', 'error')
            return redirect(request.url)

    # Retrieve list of uploaded files from Azure Blob Storage container
    uploaded_files = []
    blob_service_client = BlobServiceClient.from_connection_string(connection_string)
    container_client = blob_service_client.get_container_client(container_name)
    blobs_list = container_client.list_blobs()
    for blob in blobs_list:
        uploaded_files.append(blob.name)

    return render_template('upload.html', uploaded_files=uploaded_files)


@upload_blueprint.route('/download/<string:filename>', methods=['GET'])
def download(filename):
    try:
        # Download the file from Azure Blob Storage
        blob_service_client = BlobServiceClient.from_connection_string(connection_string)
        container_client = blob_service_client.get_container_client(container_name)
        blob_client = container_client.get_blob_client(filename)

        # Get the content type of the file
        content_type = blob_client.get_blob_properties().content_settings.content_type

        # Read the file content
        file_content = blob_client.download_blob().readall()

        # Create a response with the file content
        response = make_response(file_content)

        # Set the appropriate MIME type and attachment filename for the response
        response.headers['Content-Type'] = content_type
        response.headers['Content-Disposition'] = f'attachment; filename="{filename}"'

        return response

    except Exception as e:
        flash(f'An error occurred while downloading the file: {e}', 'error')
        return redirect(url_for('upload.upload'))


@upload_blueprint.route('/delete/<string:filename>', methods=['GET'])
def delete(filename):
    try:
        # Delete the file from Azure Blob Storage
        blob_service_client = BlobServiceClient.from_connection_string(connection_string)
        container_client = blob_service_client.get_container_client(container_name)
        blob_client = container_client.get_blob_client(filename)
        blob_client.delete_blob()

        flash('File deleted successfully!', 'success')
        return redirect(url_for('upload.upload'))

    except Exception as e:
        flash(f'An error occurred while deleting the file: {e}', 'error')
        return redirect(url_for('upload.upload'))

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container">
        <h1>Login</h1>
        <!-- Display flash messages -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <form action="" method="post">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            <button type="submit">Login</button>
        </form>
        <a href="{{ url_for('auth.signup') }}">Not registered? Sign up</a>
    </div>
</body>
</html>

app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
</head>
<body>
    <div class="container">
        <h1>Signup</h1>
        <form action="" method="post">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
            <label for="email">Email Address:</label>
            <input type="email" id="email" name="email" required>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
            <label for="confirm_password">Confirm Password:</label>
            <input type="password" id="confirm_password" name="confirm_password" required>
<!--            <input type="checkbox" id="terms" name="terms" required>-->
<!--            <label for="terms">I agree to the <a href="/terms">Terms</a>.</label>-->
<!--            <input type="checkbox" id="privacy_policy" name="privacy_policy" required>-->
<!--            <label for="privacy_policy">I acknowledge the <a href="/privacy">privacy policy</a>.</label>-->
            <button type="submit">SignUp</button>
        </form>
                <a href="{{ url_for('auth.login') }}">Already Registered?  Login</a>

    </div>
</body>
</html>

app/templates/upload.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>File Upload</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>

<body>
    <div class="container">

        <h1>File Upload</h1>
        <!-- Logout button -->
                <div class="alert text-right" style="background-color: #d4edda; color: #155724; border-color: #c3e6cb;" role="alert">
              <form action="{{ url_for('auth.logout') }}" method="post" >
            <button type="submit" class="btn btn-danger">Logout</button>
        </form>
        </div>




        <!-- Display flashed messages -->
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                <div class="alert" style="background-color: #d4edda; color: #155724; border-color: #c3e6cb;" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}

        <!-- Upload form -->
        <form action="" method="post" enctype="multipart/form-data">
            <label for="file">Choose a file:</label>
            <input type="file" id="file" name="file" required>
            <button type="submit">Upload</button>
        </form>

        <hr>

        <!-- Uploaded files -->
        <h2>Uploaded Files</h2>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>File Name</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for file in uploaded_files %}
                <tr>
                    <td>{{ file }}</td>
                    <td>
                        <a href="{{ url_for('upload.download', filename=file) }}" class="btn btn-success" download>Download</a>
                        <a href="{{ url_for('upload.delete', filename=file) }}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


    </div>
</body>

</html>